# Generated by Django 6.0.3 on 2026-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_import_source_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp de quando os volumes foram confirmados pelo operador.', null=True, verbose_name='Data da Confirmação'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp de quando o pedido foi marcado como expedido.', null=True, verbose_name='Data da Expedição'),
        ),
    ]
