# Generated by Django 6.0.3 on 2026-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_audit_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='erp_volume_sync_error',
            field=models.TextField(blank=True, help_text='Detalhes do erro caso a sincronização falhe.', verbose_name='Erro Sincronização ERP'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_volume_sync_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Sincronizado'), ('error', 'Erro')], default='pending', help_text='Status do envio do volume para a API do ERP.', max_length=10, verbose_name='Sincronização ERP'),
        ),
    ]
