# Generated by Django 6.0.3 on 2026-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_sync', '0002_add_last_checked_at_and_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='erpsynclog',
            name='erp_sync_log_date_branches_uniq',
        ),
        migrations.AddField(
            model_name='erpsynclog',
            name='search_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Parâmetros extras usados na busca (ex: order_id).', verbose_name='Filtros de Busca'),
        ),
        migrations.AddField(
            model_name='erpsynclog',
            name='search_mode',
            field=models.CharField(choices=[('date', 'Por Data'), ('order', 'Por Pedido'), ('prenote', 'Por Prenota')], default='date', max_length=10, verbose_name='Modo de Busca'),
        ),
        migrations.AddField(
            model_name='erpsynclog',
            name='triggered_by',
            field=models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='erpsynclog',
            name='sync_date',
            field=models.DateField(blank=True, help_text='Data dos pedidos consultados na API.', null=True, verbose_name='Data Sincronizada'),
        ),
    ]
