# Generated by Django 6.0.3 on 2026-03-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('cliente_nome', models.CharField(max_length=200)),
                ('endereco_logradouro', models.CharField(max_length=200)),
                ('endereco_numero', models.CharField(max_length=50)),
                ('endereco_bairro', models.CharField(max_length=100)),
                ('endereco_cidade', models.CharField(max_length=100)),
                ('endereco_uf', models.CharField(max_length=2)),
                ('endereco_cep', models.CharField(max_length=20)),
                ('rota', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ticket_printer.pedido')),
            ],
            options={
                'db_table': 'pedido_itens',
            },
        ),
        migrations.CreateModel(
            name='PedidoVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_numero', models.IntegerField()),
                ('total_volumes', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='ticket_printer.pedido')),
            ],
            options={
                'db_table': 'pedido_volumes',
            },
        ),
        migrations.CreateModel(
            name='VolumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_neste_volume', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_printer.pedidoitem')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rateados', to='ticket_printer.pedidovolume')),
            ],
            options={
                'db_table': 'volume_itens',
            },
        ),
    ]
