# Generated by Django 6.0.3 on 2026-03-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_printer', '0005_importbatch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedidos_picking_numero_pedido_key',
        ),
        migrations.RemoveConstraint(
            model_name='pedidoitem',
            name='pedido_itens_pedido_id_codigo_produto_descricao_linha_orige_key',
        ),
        migrations.RemoveConstraint(
            model_name='pedidovolume',
            name='pedido_volumes_pedido_id_volume_num_key',
        ),
        migrations.RemoveConstraint(
            model_name='volumeitem',
            name='volume_itens_volume_id_item_id_key',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='ix_pedidos_picking',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='ix_pedidos_pedido',
        ),
        migrations.RemoveIndex(
            model_name='pedidoitem',
            name='ix_itens_pedido',
        ),
        migrations.RemoveIndex(
            model_name='pedidovolume',
            name='ix_volumes_pedido',
        ),
        migrations.RemoveIndex(
            model_name='volumeitem',
            name='ix_volume_itens_volume',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidovolume',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('picking', 'numero_pedido')},
        ),
        migrations.AlterUniqueTogether(
            name='pedidoitem',
            unique_together={('pedido', 'codigo_produto', 'descricao', 'linha_origem')},
        ),
        migrations.AlterUniqueTogether(
            name='pedidovolume',
            unique_together={('pedido', 'volume_num')},
        ),
        migrations.AlterUniqueTogether(
            name='volumeitem',
            unique_together={('volume', 'item')},
        ),
    ]
