# Generated by Django 6.0.3 on 2026-06-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_jid', models.CharField(help_text='ID único do WhatsApp (ex: 5521999999999@s.whatsapp.net)', max_length=100, unique=True)),
                ('push_name', models.CharField(blank=True, help_text='Nome definido pelo usuário no WhatsApp', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone limpo (só dígitos)', max_length=50, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato WhatsApp',
                'verbose_name_plural': 'Contatos WhatsApp',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do vendedor/instância (ex: joao-vendedor)', max_length=100, unique=True)),
                ('connection_status', models.CharField(choices=[('open', 'Conectado'), ('connecting', 'Conectando'), ('close', 'Desconectado')], default='close', max_length=20)),
                ('qr_code_base64', models.TextField(blank=True, help_text='Último QR Code gerado para conexão', null=True)),
                ('owner_number', models.CharField(blank=True, help_text='Número de telefone do dono da instância', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instância WhatsApp',
                'verbose_name_plural': 'Instâncias WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID da mensagem na API do WhatsApp', max_length=255, unique=True)),
                ('from_me', models.BooleanField(default=False, help_text='True se a mensagem foi enviada pelo vendedor')),
                ('message_type', models.CharField(default='conversation', help_text='conversation, image, audio, etc', max_length=50)),
                ('content', models.TextField(blank=True, help_text='Conteúdo em texto da mensagem', null=True)),
                ('timestamp', models.DateTimeField(help_text='Data e hora exata em que a mensagem foi enviada/recebida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_tracking.whatsappcontact')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_tracking.whatsappinstance')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-timestamp'],
            },
        ),
    ]
