# Generated by Django 6.0.3 on 2026-06-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ex: 'VIP', 'Black Friday', 'B2B'", max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Cor em HEX (ex: #3B82F6)', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag de Contato',
                'verbose_name_plural': 'Tags de Contatos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='whatsapp_tracking.contacttag'),
        ),
    ]
