# Generated by Django 6.0.3 on 2026-06-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_tracking', '0002_contacttag_whatsappcontact_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome interno da campanha', max_length=150)),
                ('message_template', models.TextField(help_text='Mensagem a ser enviada. Você pode usar {nome} para inserir o nome do lead dinamicamente.')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('processing', 'Processando (Em Envio)'), ('completed', 'Concluída'), ('paused', 'Pausada')], default='draft', max_length=20)),
                ('csv_file', models.FileField(blank=True, help_text='Upload opcional de CSV (Apenas 1 coluna contendo os números de telefone).', null=True, upload_to='campaigns_csv/')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Deixe em branco para disparar assim que o status for alterado para Processando.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(help_text='Instância que fará os disparos', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='whatsapp_tracking.whatsappinstance')),
                ('target_tags', models.ManyToManyField(blank=True, help_text='Filtrar alvos automaticamente pelas Tags selecionadas.', to='whatsapp_tracking.contacttag')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas em Massa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaignTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Motivo em caso de falha.', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Horário em que o celery agendou/executou este disparo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='whatsapp_tracking.whatsappcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='whatsapp_tracking.whatsappcontact')),
            ],
            options={
                'verbose_name': 'Alvo da Campanha',
                'verbose_name_plural': 'Alvos da Campanha',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
