# Generated by Django 6.0.3 on 2026-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_tracking', '0003_whatsappcampaign_whatsappcampaigntarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
