# Generated by Django 6.0.3 on 2026-06-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_tracking', '0004_alter_whatsappcampaign_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do supervisor', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor responsável por este vendedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='whatsapp_tracking.supervisor'),
        ),
    ]
